create table AttributeValue (attribute_type varchar(31) not null, id integer not null, value integer, primary key (id));
create table Backgrounds (id integer not null, rating integer, specialization varchar(255), background integer, character_id integer, primary key (id));
create table Backgrounds_Focuses (CharacterBackground_id integer not null, focuses varchar(255));
create table Disciplines (id integer not null, rating integer, trait integer not null, character_id integer, primary key (id));
create table ExperienceAward (id integer not null, awardedFor varchar(255), awardedOn datetime, experience integer, event_id integer, primary key (id));
create table Flaws (id integer not null, specialization varchar(255), trait integer not null, character_id integer, primary key (id));
create table Merits (id integer not null, specialization varchar(255), trait integer not null, character_id integer, primary key (id));
create table Patronage (id integer not null, expiration datetime, original_username varchar(255), year integer, primary key (id));
create table Patronage_payments (Patronage_id integer not null, payment_amount decimal(19,2), payment_date datetime, payment_receipt_identifier varchar(255), payment_type integer, order_by integer not null, primary key (Patronage_id, order_by));
create table PlayerCharacter (id integer not null, approvalStatus integer, awardedXp integer, baseXp integer, bloodline integer, clan integer, groundXp integer, mental_attribute integer, name varchar(255), physical_attribute integer, primary_necromantic_path integer, primary_thaumaturgical_path integer, setting integer, social_attribute integer, appliedSpentXp integer, pendingSpentXp integer, primary key (id));
create table PlayerCharacterOwnership (id integer not null, venue integer, character_id integer, user integer, primary key (id));
create table PlayerCharacterOwnership_statusChanges (PlayerCharacterOwnership_id integer not null, changedOn datetime, status integer, order_by integer not null, primary key (PlayerCharacterOwnership_id, order_by));
create table PlayerCharacter_AppliedTraitChanges (PlayerCharacter_id integer not null, appliedTraitChanges_id bigint not null, order_by integer not null, primary key (PlayerCharacter_id, order_by));
create table PlayerCharacter_ExperienceAward (PlayerCharacter_id integer not null, experienceAwards_id integer not null);
create table PlayerCharacter_RequestedTraitChanges (PlayerCharacter_id integer not null, requesedTraitChanges_id bigint not null, order_by integer not null, primary key (PlayerCharacter_id, order_by));
create table PlayerCharacter_elderPowers (PlayerCharacter_id integer not null, elderPowers integer);
create table PlayerCharacter_inClanDisciplines (PlayerCharacter_id integer not null, inClanDisciplines integer, order_by integer not null, primary key (PlayerCharacter_id, order_by));
create table PlayerCharacter_mentalAttrbuteFocuses (PlayerCharacter_id integer not null, mentalAttrbuteFocuses integer);
create table PlayerCharacter_necromanticRituals (PlayerCharacter_id integer not null, necromanticRituals integer);
create table PlayerCharacter_physicalAttributeFocuses (PlayerCharacter_id integer not null, physicalAttributeFocuses integer);
create table PlayerCharacter_socialAttributeFocuses (PlayerCharacter_id integer not null, socialAttributeFocuses integer);
create table PlayerCharacter_techniques (PlayerCharacter_id integer not null, techniques integer);
create table PlayerCharacter_thaumaturgicalRituals (PlayerCharacter_id integer not null, thaumaturgicalRituals integer);
create table Skills (id integer not null, rating integer, specialization varchar(255), skill integer, character_id integer, primary key (id));
create table Skills_Focuses (CharacterSkill_id integer not null, focuses varchar(255));
create table Status (id integer not null, specialization varchar(255), trait integer not null, character_id integer, primary key (id));
create table TraitChange_focuses (TraitChange_id bigint not null, focuses varchar(255));
create table TraitChanges (id bigint not null, cost integer, rating integer, specialization varchar(255), remove bit, traitOrdinal integer, traitTypeOrdinal integer, child_id bigint, primary key (id));
create table Troupe (id integer not null, deleted_at datetime, name varchar(255), venue integer, primary key (id));
create table TroupeEvent (id integer not null, eventDate datetime, status integer, name varchar(255), troupe_id integer, primary key (id));
create table TroupeEvent_Attendance (event_id integer not null, playerCharacterOwnership_id integer not null, primary key (event_id, playerCharacterOwnership_id));
create table Troupe_PlayerCharacters (troupe_id integer not null, playerCharacter_id integer not null, primary key (troupe_id, playerCharacter_id));
create table Troupe_StorytellerUsers (troupe_id integer not null, user_id integer not null, primary key (troupe_id, user_id));
create table User (id integer not null, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id));
create table UserPasswordResetToken (id integer not null, email varchar(255), expiresAt datetime, resetToken varchar(255), primary key (id));
create table User_Patronage (patronage_id integer, user_id integer, primary key (patronage_id));
create table User_roles (User_id integer not null, roles integer);
create table VenueEvent (id integer not null, eventDate datetime, status integer, name varchar(255), venue integer, primary key (id));
create table VenueEvent_Attendance (event_id integer not null, playerCharacterOwnership_id integer not null, primary key (event_id, playerCharacterOwnership_id));
alter table PlayerCharacter_AppliedTraitChanges add constraint PlayerCharacter_AppliedTraitChanges_UC  unique (appliedTraitChanges_id);
alter table PlayerCharacter_ExperienceAward add constraint PlayerCharacter_ExperienceAwards_UC  unique (experienceAwards_id);
alter table PlayerCharacter_RequestedTraitChanges add constraint PlayerCharacter_RequestedTraitChanges_UC  unique (requesedTraitChanges_id);
alter table TroupeEvent add constraint UK_t1swkkfx3s7fqmcuqpbothmev  unique (id);
alter table User_Patronage add constraint User_Patronage_UC  unique (patronage_id, user_id);
alter table VenueEvent add constraint UK_9botmoi3bujn094hqient137o  unique (id);
alter table Backgrounds add constraint PlayerCharacter_Backgrounds_FK foreign key (character_id) references PlayerCharacter (id);
alter table Backgrounds_Focuses add constraint CharacterBackground_focuses_FK foreign key (CharacterBackground_id) references Backgrounds (id);
alter table Disciplines add constraint PlayerCharacter_Disciplines_FK foreign key (character_id) references PlayerCharacter (id);
alter table Flaws add constraint PlayerCharacter_Flaws_FK foreign key (character_id) references PlayerCharacter (id);
alter table Merits add constraint PlayerCharacter_Merits_FK foreign key (character_id) references PlayerCharacter (id);
alter table Patronage_payments add constraint Patronage_PatronagePaymentReceipt_FK foreign key (Patronage_id) references Patronage (id);
alter table PlayerCharacterOwnership add constraint PlayerCharacterOwnership_PlayerCharacter_FK foreign key (character_id) references PlayerCharacter (id);
alter table PlayerCharacterOwnership add constraint PlayerCharacterOwnership_User_FK foreign key (user) references User (id);
alter table PlayerCharacterOwnership_statusChanges add constraint PlayerCharacterOwnership_PlayerStatusChange_FK foreign key (PlayerCharacterOwnership_id) references PlayerCharacterOwnership (id);
alter table PlayerCharacter_AppliedTraitChanges add constraint AppliedTraitChanges_PlayerCharacter_FK foreign key (appliedTraitChanges_id) references TraitChanges (id);
alter table PlayerCharacter_AppliedTraitChanges add constraint PlayerCharacter_AppliedTraitChanges_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_ExperienceAward add constraint ExperienceAwards_PlayerCharacter_FK foreign key (experienceAwards_id) references ExperienceAward (id);
alter table PlayerCharacter_ExperienceAward add constraint PlayerCharacter_ExperienceAwards_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_RequestedTraitChanges add constraint RequestedTraitChanges_PlayerCharacter_FK foreign key (requesedTraitChanges_id) references TraitChanges (id);
alter table PlayerCharacter_RequestedTraitChanges add constraint PlayerCharacter_RequestedTraitChanges_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_elderPowers add constraint PlayerCharacter_ElderPowers_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_inClanDisciplines add constraint PlayerCharacter_InClanDisciplines_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_mentalAttrbuteFocuses add constraint PlayerCharacter_MentalAttributeFocuses_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_necromanticRituals add constraint PlayerCharacter_CharacterNecromanticRituals_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_physicalAttributeFocuses add constraint PlayerCharacter_PhysicalAttributeFocuses_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_socialAttributeFocuses add constraint PlayerCharacter_SocialAttributeFocuses_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_techniques add constraint PlayerCharacter_Techniques_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table PlayerCharacter_thaumaturgicalRituals add constraint PlayerCharacter_CharacterThaumaturgicalRituals_FK foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table Skills add constraint PlayerCharacter_Skills_FK foreign key (character_id) references PlayerCharacter (id);
alter table Skills_Focuses add constraint CharacterSkill_focuses_FK foreign key (CharacterSkill_id) references Skills (id);
alter table Status add constraint PlayerCharacter_Status_FK foreign key (character_id) references PlayerCharacter (id);
alter table TraitChange_focuses add constraint TraitQualities_focuses_FK foreign key (TraitChange_id) references TraitChanges (id);
alter table TraitChanges add constraint TraitChange_ChildTraitChange_FK foreign key (child_id) references TraitChanges (id);
alter table TroupeEvent add constraint TroupeEvent_Troupe_FK foreign key (troupe_id) references Troupe (id);
alter table TroupeEvent_Attendance add constraint PlayerCharacterOwnership_TroupeEvent_FK foreign key (playerCharacterOwnership_id) references PlayerCharacterOwnership (id);
alter table TroupeEvent_Attendance add constraint TroupeEvent_PlayerCharacterOwnership_FK foreign key (event_id) references TroupeEvent (id);
alter table Troupe_PlayerCharacters add constraint PlayerCharacters_Troupe_FK foreign key (playerCharacter_id) references PlayerCharacter (id);
alter table Troupe_PlayerCharacters add constraint Troupe_PlayerCharacters_FK foreign key (troupe_id) references Troupe (id);
alter table Troupe_StorytellerUsers add constraint StorytellerUsers_Troupe_FK foreign key (user_id) references User (id);
alter table Troupe_StorytellerUsers add constraint Troupe_StorytellerUsers_FK foreign key (troupe_id) references Troupe (id);
alter table User_Patronage add constraint User_Patronage_FK foreign key (patronage_id) references Patronage (id);
alter table User_Patronage add constraint Patronage_User_FK foreign key (user_id) references User (id);
alter table User_roles add constraint User_Roles_FK foreign key (User_id) references User (id);
alter table VenueEvent_Attendance add constraint PlayerCharacterOwnership_VenueEvent_FK foreign key (playerCharacterOwnership_id) references PlayerCharacterOwnership (id);
alter table VenueEvent_Attendance add constraint VenueEvent_PlayerCharacterOwnership_FK foreign key (event_id) references VenueEvent (id);
create table ID_Sequences ( sequence_name varchar(255),  sequence_next_hi_value bigint );
