displayableValues = [[[[]]]];
displayableValues['en_US'] = [[[]]];
displayableValues['en_US']['Vampire'] = [[]];
displayableValues['en_US']['User'] = [[]];

var i = -1;
displayableValues['en_US']['Vampire']['Clan'] = [];
displayableValues['en_US']['Vampire']['Clan'][++i] = "Assamite";              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Brujah";                
displayableValues['en_US']['Vampire']['Clan'][++i] = "Follower of Set";       
displayableValues['en_US']['Vampire']['Clan'][++i] = "Gangrel";               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Giovanni";              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Lasombra";              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Malkavian";             
displayableValues['en_US']['Vampire']['Clan'][++i] = "Nosferatu";             
displayableValues['en_US']['Vampire']['Clan'][++i] = "Toreador";              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Tremere";               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Tzimisce";              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Ventrue";               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Catiff";                
displayableValues['en_US']['Vampire']['Clan'][++i] = "Baali";                 
displayableValues['en_US']['Vampire']['Clan'][++i] = "Cappadocian";           
displayableValues['en_US']['Vampire']['Clan'][++i] = "Ravnos";                
displayableValues['en_US']['Vampire']['Clan'][++i] = "Salubri";               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Daughter of Cacophony"; 
displayableValues['en_US']['Vampire']['Clan'][++i] = "Gargoyle";              

var i = -1;
displayableValues['en_US']['Vampire']['Bloodline'] = [];
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Vizier"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Sorcerer"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "True Brujah"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Tlaclque"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Viper"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Coyote"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Noiad"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Ahrimane"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Premascine"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Kisayd"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Ananke"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Knight of the Moon"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Ishtarri"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Volgirre"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Telyav"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Carpathian"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Koldun"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Crusader"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Angellis Ater"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Samedi"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Lamia"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Brahman"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Healer"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"

var i = -1;
displayableValues['en_US']['Vampire']['Discipline'] = [];
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Animalism";
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Auspex";       
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Celerity";     
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Chimerstry";   
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Daimoinon";    
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Dementation";  
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Dominate";     
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Fortitude";    
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Melpominee";   
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Mytherceria";  
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Obeah";        
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Obfuscate";    
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Obtenebration";
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Potence";      
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Presence";     
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Protean";      
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Quietus";      
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Serpentis";    
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Temporsis";    
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Thanatosis";   
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Valeren";      
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Vicissitude";  
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Visceratika";  
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Sepulchre Path";
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Bone Path";     
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Ash Path";      
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Mortis Path";
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Path of Blood";            
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Path of Conjuring";        
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Path of Corruption";       
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Path of Elemental Mastery";
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Lure of Flames";           
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Movement of the Mind";     
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Path of Technomancy";      
displayableValues['en_US']['Vampire']['Discipline'][++i] = "Path of Weather Mastery";

var i = -1;
displayableValues['en_US']['Vampire']['PowerType'] = [];
displayableValues['en_US']['Vampire']['PowerType'][++i] = "Discipline";
displayableValues['en_US']['Vampire']['PowerType'][++i] = "Necromancy";       
displayableValues['en_US']['Vampire']['PowerType'][++i] = "Thaumaturgy";     

var i = -1;
displayableValues['en_US']['Vampire']['ElderPower'] = [];
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Crimson Fury";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Intimidate the Beast";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Clairvoyance";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Psychic assault";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Quickness";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Projectile";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Shared Nightmare";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Army of Apparitions";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Infernal Compact";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Lingering Malaise";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Deny";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Mass Manipulation";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Tyrant's Gaze";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Personal Armor";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Repair the Undead Flesh";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Shattering Crescendo";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Persistent Echo";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Steal the Mind";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Unburden the Beastial Soul";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Cache";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Phantom Hunter";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Shadowstep";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Shadow Twin";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Force";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Flick";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Paralyzing Glance";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Love";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Earth Control";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Shape Mastery";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Blood Sweat";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Baal's Bloody Talons";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Seed of Corruption";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Divine Image";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Kiss of Lachesis";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Corrupt the Flesh";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Fiery Agony";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Breath of the Dragon";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Acid Blood";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Bulwark";
displayableValues['en_US']['Vampire']['ElderPower'][++i] = "Furnace of Steel";

var i = -1;
displayableValues['en_US']['Vampire']['Technique'] = [];
displayableValues['en_US']['Vampire']['Technique'][++i] = "An Da Shealladh";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Animal Succulence";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Animal Swarm";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Armor of Darkness";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Banshee's Wail";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Blind the Sun";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Bull's Eye";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Control the Savage Beast";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Death's Grip";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Denial of Aphrodite's Favor";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Devious Feint";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Echo Psychosis";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Fearful Blow";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Feast of Shadows";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Fenrir's Boon";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Fist of Stone";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Flames Bane";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Guardian Lion";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Instinctive Command";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Ligeia's Lament";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Mercurial Vitality";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Monologue";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Misplaced Affection";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Misleading Wounds";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Nightingales Song";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Quickened Blood";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Radiant Gaze";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Reflection of Endurance";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Reflection of Mercy";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Relentless Pursuit";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Retain the Quick Blood";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Second Wind";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Sympathetic Agony";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Telepathic Directive";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Unnatural Grace";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Visions of the True Form";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Will to Survive";
displayableValues['en_US']['Vampire']['Technique'][++i] = "Wolf's Blood";

var i = -1;
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'] = [];
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Blood Mastery";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Bind the Accusing Tongue";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Communicate with Kindred Sire";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Defense of the Sacred Haven";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Engaging the Vessel of Transference";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Illuminate the Trail of Prey";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Principal Focus of Vitae Infusion";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Warding Circle";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Banish Big Brother";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Burning Blade";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Craft Bloodstone";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Eyes of the Nighthawk";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Illusion of Peaceful Death";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Machine Blitz";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Recure of the Homeland";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Detect the Hidden Observer";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Flesh of Fiery Touch";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Incorporeal Passage";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Mirror of Second Sight";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Pavis of Foul Presence";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Soul of the Homunculi";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Shaft of Belated Quiescence";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Innocence of the Child's Heart";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Mirror Walk";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Severed Hand";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Scry";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Blood Contract";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Cobra's Favor";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Paper Flesh";
displayableValues['en_US']['Vampire']['ThaumaturgicalRitual'][++i] = "Stone of the True Form";

var i = -1;
displayableValues['en_US']['Vampire']['NecromanticRitual'] = [];
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Call of the Hungry Dead";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Circle of Cerberus";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Dark Assistant";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Eyes of the Grave";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Smoking Mirror";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Warping the Morbid Visage";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Black Blood";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Din of the Damned";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Sepulchral Beacon";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Stained Sight";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Scales of Maat";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Moldering Presence";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Rise, Cerberus";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Spirit Beacon";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "The Servant Undying";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Bastone Diabolico";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Lethe's Water";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Ritual of Xipe Totec";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Strength of Rotten Flesh";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Chill of Oblivion";
displayableValues['en_US']['Vampire']['NecromanticRitual'][++i] = "Weight of the Tomb";

var i = -1;
displayableValues['en_US']['Vampire']['Background'] = [];
displayableValues['en_US']['Vampire']['Background'][++i] = "Allies";
displayableValues['en_US']['Vampire']['Background'][++i] = "Alternate Identity";
displayableValues['en_US']['Vampire']['Background'][++i] = "Contacts" ;
displayableValues['en_US']['Vampire']['Background'][++i] = "Fame";
displayableValues['en_US']['Vampire']['Background'][++i] = "Generation";
displayableValues['en_US']['Vampire']['Background'][++i] = "Haven" ;
displayableValues['en_US']['Vampire']['Background'][++i] = "Herd";
displayableValues['en_US']['Vampire']['Background'][++i] = "Elite Influence";
displayableValues['en_US']['Vampire']['Background'][++i] = "Underworld Influence";
displayableValues['en_US']['Vampire']['Background'][++i] = "Resources";
displayableValues['en_US']['Vampire']['Background'][++i] = "Retainer" ;
displayableValues['en_US']['Vampire']['Background'][++i] = "Rituals"

var i = -1;
displayableValues['en_US']['User']['PaymentType'] = [];
displayableValues['en_US']['User']['PaymentType'][++i] = "Other";
displayableValues['en_US']['User']['PaymentType'][++i] = "Paypal";
displayableValues['en_US']['User']['PaymentType'][++i] = "Award";
displayableValues['en_US']['User']['PaymentType'][++i] = "Gift";
