displayableValues = [[[[]]]];
displayableValues['en_US'] = [[[]]];
displayableValues['en_US']['Vampire'] = [[]];
displayableValues['en_US']['User'] = [[]];

var i = -1;
displayableValues['en_US']['Vampire']['Clan'] = [];
displayableValues['en_US']['Vampire']['Clan'][++i] = "Assamite",              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Brujah",                
displayableValues['en_US']['Vampire']['Clan'][++i] = "Follower of Set",       
displayableValues['en_US']['Vampire']['Clan'][++i] = "Gangrel",               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Giovanni",              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Lasombra",              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Malkavian",             
displayableValues['en_US']['Vampire']['Clan'][++i] = "Nosferatu",             
displayableValues['en_US']['Vampire']['Clan'][++i] = "Toreador",              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Tremere",               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Tzimisce",              
displayableValues['en_US']['Vampire']['Clan'][++i] = "Ventrue",               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Catiff",                
displayableValues['en_US']['Vampire']['Clan'][++i] = "Baali",                 
displayableValues['en_US']['Vampire']['Clan'][++i] = "Cappadocian",           
displayableValues['en_US']['Vampire']['Clan'][++i] = "Ravnos",                
displayableValues['en_US']['Vampire']['Clan'][++i] = "Salubri",               
displayableValues['en_US']['Vampire']['Clan'][++i] = "Daughter of Cacophony", 
displayableValues['en_US']['Vampire']['Clan'][++i] = "Gargoyle",              

var i = -1;
displayableValues['en_US']['Vampire']['Bloodline'] = [];
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Vizier"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Sorcerer"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "True Brujah"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Tlaclque"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Viper"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Coyote"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Noiad"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Ahrimane"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Premascine"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Kisayd"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Ananke"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Knight of the Moon"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Ishtarri"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Volgirre"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Telyav"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Carpathian"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Koldun"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Crusader"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Angellis Ater"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Samedi"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Lamia"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Brahman"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "Healer"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"
displayableValues['en_US']['Vampire']['Bloodline'][++i] = "None"

var i = -1;
displayableValues['en_US']['Vampire']['Background'] = [];
displayableValues['en_US']['Vampire']['Background'][++i] = "Allies";
displayableValues['en_US']['Vampire']['Background'][++i] = "Alternate Identity";
displayableValues['en_US']['Vampire']['Background'][++i] = "Contacts" ;
displayableValues['en_US']['Vampire']['Background'][++i] = "Fame";
displayableValues['en_US']['Vampire']['Background'][++i] = "Generation";
displayableValues['en_US']['Vampire']['Background'][++i] = "Haven" ;
displayableValues['en_US']['Vampire']['Background'][++i] = "Herd";
displayableValues['en_US']['Vampire']['Background'][++i] = "Elite Influence";
displayableValues['en_US']['Vampire']['Background'][++i] = "Underworld Influence";
displayableValues['en_US']['Vampire']['Background'][++i] = "Resources";
displayableValues['en_US']['Vampire']['Background'][++i] = "Retainer" ;
displayableValues['en_US']['Vampire']['Background'][++i] = "Rituals"

var i = -1;
displayableValues['en_US']['User']['PaymentType'] = [];
displayableValues['en_US']['User']['PaymentType'][++i] = "Other";
displayableValues['en_US']['User']['PaymentType'][++i] = "Paypal";
displayableValues['en_US']['User']['PaymentType'][++i] = "Award";
displayableValues['en_US']['User']['PaymentType'][++i] = "Gift";
